### ISSUE TITLE
不知道后台管理的网址

### ISSUE THREAD

**Issue by soonsoin** [a6678696/SecondHandTrade#2]
博主你好，我是个新手，想用您的项目来学习。
我现在可以用localhost：8080进入前台，可以用普通账户在前台登陆注册，但用管理员账号无法在前台登录且显示管理员账号只能在后台登陆，
但是我不知道该怎么进入后台管理的页面，请问后台管理的页面网址是多少，麻烦博主了

**Comment by a6678696** [comment]
http://localhost:8080/login.html

**Comment by soonsoin** [comment]
谢谢博主，打开了
